apiVersion: cloudrobot.kubeedge.cloudrobot.kubeedge/v1beta1
kind: RobotSync
metadata:
  labels:
    app.kubernetes.io/name: robotsync
    app.kubernetes.io/instance: robotsync-sample
    app.kubernetes.io/part-of: ospp2023
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ospp2023
  name: robotsync-sample
spec:
  # TODO(user): Add fields here
