# permissions for end users to view robots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: robot-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ospp2023
    app.kubernetes.io/part-of: ospp2023
    app.kubernetes.io/managed-by: kustomize
  name: robot-viewer-role
rules:
- apiGroups:
  - cloudrobot.kubeedge.cloudrobot.kubeedge
  resources:
  - robots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudrobot.kubeedge.cloudrobot.kubeedge
  resources:
  - robots/status
  verbs:
  - get
